/** SKAF */

#ifndef _HEAVY_CONTEXT_DEMO_HPP_
#define _HEAVY_CONTEXT_DEMO_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlCast.h"
#include "HvMath.h"
#include "HvSignalVar.h"
#include "HvControlSystem.h"
#include "HvControlVar.h"
#include "HvSignalBiquad.h"
#include "HvSignalLine.h"
#include "HvControlBinop.h"
#include "HvControlUnop.h"

class Heavy_Demo : public HeavyContext {

 public:
  Heavy_Demo(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_Demo();

  const char *getName() override { return "Demo"; }
  int getNumInputChannels() override { return 2; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;
  struct Parameter {
    struct In {
      enum ParameterIn : hv_uint32_t {
        GAIN = 0x766D1755, // GAIN
        LEVEL = 0xCD345ED7, // LEVEL
        TONE = 0x4F7510B7, // TONE
      };
    };
  };

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cBinop_hN175v6X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aW764qio_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HmJWSOop_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Le785lIN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EoHb3YCE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iVouCEnE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SMoPF1Yz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gXOrzu95_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_PSJJAonT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_O9tHaeY3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QSjWXzWd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0TEf8EWA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YBhPQsON_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_AX59Z5yS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XOlSyNeU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_UcOqlu7Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gHDllkhX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uj1YQ1hq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3r7ewWxF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JN1YNV5r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_UnpiG5UQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2jmgtUyb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_dpsQPN7J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vShNNcHu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_j2SvIlRK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dZQzhIJa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ySng467K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ufKJnRYT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dKJRSsqK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yxWn5Jtv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iw9E9YDB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FeobJl8W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Dk88YbYz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5S4Ma918_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pQ8paSg1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EIB5IWMT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_oLlAPUkn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bHWZd6lZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_oLGgGZ6t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_KSxsjeW4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_MZGfN6RU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nsXAxOri_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ae8LX2ZN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_m3rznm0e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CpfLYwj3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sQT8ilj9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Sa5Gu7Ka_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_g5v6M4PJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5prTPQCI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wJb42nRJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FLoZi4cE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KIRYzW01_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7yzgzzL3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4MoPGmz8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lKoTdWUS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SPPkIe9K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8DdosM3F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_twQGDo13_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_M9OTznrJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5EswCX6f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qNOo4TZf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iLLv6K1f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5Bts8pW5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bZDJ2hbL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_6r76R3Uy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8Ta4bKu6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EMWrwTu2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_79sgys9D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7HuhfN6o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4WV6jxLT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W15UqXYU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PzSxnT6Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_d6jwrn18_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_piC9I9kx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LwmWB2dW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_1LFcrkbz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SACXV8gt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jOXrIgcc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JWxdTxbx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3v6Nqab5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TcUGRJcg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_voqiAQxJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_zYjGeQJN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xsmSy3ag_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5A3Wd0DT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jKsOiGtY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qp5r9fKA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NBIH4wAB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_npUb2FDw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RtzU80En_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oUdGbcFc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wTbWmyOW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_k6KNaIQR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HWLuYBCM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_C4mZGe71_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_51QqEKuQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Rf5daqDl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iQ9bvhAH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_UJZION0o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_87R3epMR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_mBzIgsmW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_DlJR61mP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_LqNK4mMQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6Zf27hyu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L6zIUuL7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AOb7EYhq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CUr2uXNZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2k0eoTnN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_c0ZdOp1q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ONIzVqBU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZnCrciHK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XWOUuLCe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KH8W37Dm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_akZSWYxX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RYQnihUn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ww1eIpcB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_c2snELeA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XkmgEXil_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_sYkdpEtA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AuA0kDB0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wT4YzaXl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4fhvIyqr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WUfLUrXg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iUXkcDB8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dRkVZSH9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DGiJojUQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4jakB8m2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yNO9QYnN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aLQNO26F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3sPREXEu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_32nYS7Az_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yMUWPRDE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4lhhcbSW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yGHoebyq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9ohYEyIY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KlUYieP8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fLAanMr8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tORpSeq7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_yphUZEGv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_DJ1EeuOt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dDqByDTF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_t9ayc5QZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TwKNhDgk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kLx3Ftau_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_L3WWN4ii_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_z920SXBh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VMUWXolf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Dx41fmPL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bqwYkw07_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_slgY7Frb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ez96qfte_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NadwUy2W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FirnqbBL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gA1HtNRl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_crbi8VRm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0lyOEqEp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NzvaqSf7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5v4v9bnh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_KI5a9JjV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_y9Rhqo3t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_xHBBYD6C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QFjry6pu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aGoYrKhP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8NLwmqzn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_y7kXRK1d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_degbjoVS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TEfOcaGM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_X7z7a9vk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iE8EBlC1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dYyT8XuD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FXHL9oKI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GzkfIjmq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GZsPurIg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_liOTiyoM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TZpo0lWN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fT0CaLVa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pZnfx1Yd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9C3tm3mB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jOqO8OCI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DZmLEM9v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WpiWhdnZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_pOLc7XwH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_8i1562zA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AkpWPiyH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AX8SSaJR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XT0LGB15_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FhcQ324U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wCznSVn2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_602saeqb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Obvmw9Yp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_iQsx8ljb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1IwbWHjR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_p3ITkIef_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_k7p4f6d7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0YvET57Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xu5vTAsj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_OeZuuyTX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RGdVTCQ7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_veYfOdjE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aqwb1dBN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rO1f2CL0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_94yBfUx7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_130W0LOJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5HO4XSwn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Whp6K7jV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ikddMeH8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6mh0z93n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ljFO5M0P_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BYW0vwYb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uPNhs02y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uD0Int4n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ci121zqP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UVqpGJEF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CsfyW0k1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Vd3rt7OR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XbwrCuil_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_g8C0Ttuu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_F1SRPT9k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_N07CfiKL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_U2WRfHyH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uNUw0m7V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_11fIRQKx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_AN0yC9uK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_degb2POW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_InywLZFi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Csf4JUWc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AQ6prPzG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dqG0WiIN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tl5uxDf9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bpzn7K3D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LllTY5xA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WWOjBzef_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BBS2Ffar_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_o4UjCe4N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_f9oYC891_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5U0LLzVB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hPkGBaPV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FLXyATWu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DvCAKvOp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gdcOiDyK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mURlxLdP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_hbefOWQN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_10yeAp0p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_yPUDqhHk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_q0lKwzZa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_GBiDKUR2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_W8EDRsIL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Jq2GqDQ9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_550x0ymP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_OdRYtfti_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_HMUF2a65_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_mudTdE8e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_HpvRRui9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_geKqT2jq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_w17VJPx8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_FLL3uUUz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_zHwhhf5Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalLine sLine_34biuOpu;
  SignalLine sLine_GVC8EOv0;
  SignalLine sLine_JMLI4xvg;
  SignalLine sLine_7XIzATsd;
  SignalLine sLine_dVPDUY3B;
  SignalBiquad sBiquad_s_vgIl2uDb;
  SignalLine sLine_SyuUHNy5;
  SignalLine sLine_ARlO2hTf;
  SignalLine sLine_ClX8cKq8;
  SignalLine sLine_zuxmJvm6;
  SignalLine sLine_Grklo6Fs;
  SignalBiquad sBiquad_s_cT6iV1ap;
  SignalLine sLine_NTDMXVlU;
  SignalLine sLine_hUgrnJZu;
  SignalLine sLine_Xb3UTKz6;
  SignalLine sLine_OIxno7BL;
  SignalLine sLine_ekTSyBMf;
  SignalBiquad sBiquad_s_st26xr2o;
  SignalLine sLine_cfyVNX2K;
  SignalLine sLine_i4AxKAeE;
  SignalLine sLine_thgcuVbz;
  SignalLine sLine_XoQIKPb7;
  SignalLine sLine_MjvDqqKv;
  SignalBiquad sBiquad_s_C559XdIe;
  ControlBinop cBinop_hN175v6X;
  ControlBinop cBinop_aW764qio;
  ControlVar cVar_HmJWSOop;
  ControlVar cVar_Le785lIN;
  ControlBinop cBinop_EoHb3YCE;
  ControlBinop cBinop_iVouCEnE;
  ControlBinop cBinop_SMoPF1Yz;
  ControlBinop cBinop_gXOrzu95;
  ControlBinop cBinop_O9tHaeY3;
  ControlBinop cBinop_QSjWXzWd;
  ControlBinop cBinop_0TEf8EWA;
  ControlBinop cBinop_gHDllkhX;
  ControlBinop cBinop_uj1YQ1hq;
  ControlBinop cBinop_3r7ewWxF;
  ControlVar cVar_2jmgtUyb;
  ControlBinop cBinop_vShNNcHu;
  ControlBinop cBinop_j2SvIlRK;
  ControlBinop cBinop_dZQzhIJa;
  ControlBinop cBinop_ySng467K;
  ControlBinop cBinop_ufKJnRYT;
  ControlBinop cBinop_dKJRSsqK;
  ControlBinop cBinop_yxWn5Jtv;
  ControlBinop cBinop_iw9E9YDB;
  ControlBinop cBinop_FeobJl8W;
  ControlBinop cBinop_Dk88YbYz;
  ControlBinop cBinop_5S4Ma918;
  ControlBinop cBinop_pQ8paSg1;
  ControlBinop cBinop_EIB5IWMT;
  ControlBinop cBinop_qNOo4TZf;
  ControlBinop cBinop_iLLv6K1f;
  ControlVar cVar_5Bts8pW5;
  ControlBinop cBinop_bZDJ2hbL;
  ControlBinop cBinop_8Ta4bKu6;
  ControlBinop cBinop_EMWrwTu2;
  ControlBinop cBinop_7HuhfN6o;
  ControlVar cVar_4WV6jxLT;
  ControlBinop cBinop_W15UqXYU;
  ControlBinop cBinop_piC9I9kx;
  ControlBinop cBinop_LwmWB2dW;
  ControlVar cVar_1LFcrkbz;
  ControlBinop cBinop_SACXV8gt;
  ControlBinop cBinop_jOXrIgcc;
  ControlBinop cBinop_3v6Nqab5;
  ControlBinop cBinop_xsmSy3ag;
  ControlBinop cBinop_5A3Wd0DT;
  ControlBinop cBinop_jKsOiGtY;
  ControlBinop cBinop_RtzU80En;
  ControlBinop cBinop_oUdGbcFc;
  ControlBinop cBinop_wTbWmyOW;
  ControlBinop cBinop_k6KNaIQR;
  ControlBinop cBinop_HWLuYBCM;
  ControlBinop cBinop_C4mZGe71;
  ControlBinop cBinop_51QqEKuQ;
  ControlBinop cBinop_Rf5daqDl;
  ControlBinop cBinop_iQ9bvhAH;
  ControlVar cVar_AuA0kDB0;
  ControlBinop cBinop_wT4YzaXl;
  ControlBinop cBinop_WUfLUrXg;
  ControlBinop cBinop_iUXkcDB8;
  ControlBinop cBinop_dRkVZSH9;
  ControlBinop cBinop_DGiJojUQ;
  ControlVar cVar_yNO9QYnN;
  ControlBinop cBinop_aLQNO26F;
  ControlBinop cBinop_3sPREXEu;
  ControlVar cVar_yMUWPRDE;
  ControlBinop cBinop_4lhhcbSW;
  ControlBinop cBinop_yGHoebyq;
  ControlBinop cBinop_KlUYieP8;
  ControlBinop cBinop_fLAanMr8;
  ControlBinop cBinop_tORpSeq7;
  ControlBinop cBinop_TwKNhDgk;
  ControlBinop cBinop_kLx3Ftau;
  ControlBinop cBinop_L3WWN4ii;
  ControlBinop cBinop_Dx41fmPL;
  ControlBinop cBinop_bqwYkw07;
  ControlBinop cBinop_slgY7Frb;
  ControlBinop cBinop_Ez96qfte;
  ControlBinop cBinop_NadwUy2W;
  ControlBinop cBinop_FirnqbBL;
  ControlBinop cBinop_gA1HtNRl;
  ControlBinop cBinop_crbi8VRm;
  ControlBinop cBinop_0lyOEqEp;
  ControlVar cVar_AkpWPiyH;
  ControlBinop cBinop_AX8SSaJR;
  ControlBinop cBinop_FhcQ324U;
  ControlBinop cBinop_1IwbWHjR;
  ControlBinop cBinop_p3ITkIef;
  ControlBinop cBinop_k7p4f6d7;
  ControlBinop cBinop_OeZuuyTX;
  ControlBinop cBinop_RGdVTCQ7;
  ControlVar cVar_veYfOdjE;
  ControlBinop cBinop_aqwb1dBN;
  ControlBinop cBinop_rO1f2CL0;
  ControlBinop cBinop_94yBfUx7;
  ControlVar cVar_130W0LOJ;
  ControlBinop cBinop_5HO4XSwn;
  ControlBinop cBinop_Whp6K7jV;
  ControlBinop cBinop_6mh0z93n;
  ControlBinop cBinop_ljFO5M0P;
  ControlBinop cBinop_uPNhs02y;
  ControlBinop cBinop_uD0Int4n;
  ControlBinop cBinop_ci121zqP;
  ControlBinop cBinop_UVqpGJEF;
  ControlBinop cBinop_CsfyW0k1;
  ControlBinop cBinop_Vd3rt7OR;
  ControlBinop cBinop_XbwrCuil;
  ControlBinop cBinop_g8C0Ttuu;
  ControlBinop cBinop_F1SRPT9k;
  ControlBinop cBinop_N07CfiKL;
  ControlBinop cBinop_DvCAKvOp;
  ControlBinop cBinop_gdcOiDyK;
  ControlBinop cBinop_mURlxLdP;
  SignalVarf sVarf_3nf2xQlc;
  SignalVarf sVarf_xQ04v8Xu;
};

#endif // _HEAVY_CONTEXT_DEMO_HPP_
